# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for CodexJ
Bundles FastAPI backend with embedded React frontend
"""

import sys
from pathlib import Path

block_cipher = None
PROJECT_ROOT = Path(SPEC).parent
BACKEND_DIR = PROJECT_ROOT / "backend"
APP_DIR = BACKEND_DIR / "app"

# Collect all data files
datas = [
    # Frontend static files (built by Vite, copied by build.py)
    (str(APP_DIR / "static"), "static"),
    # Help documentation
    (str(APP_DIR / "help.md"), "."),
    # Build config (generated by build.py)
    (str(APP_DIR / "build_config.py"), "."),
]

# Hidden imports required by FastAPI/Uvicorn ecosystem
hiddenimports = [
    # Uvicorn core
    "uvicorn",
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.loops.asyncio",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.http.httptools_impl",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.protocols.websockets.websockets_impl",
    "uvicorn.protocols.websockets.wsproto_impl",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "uvicorn.lifespan.off",
    # FastAPI/Starlette
    "fastapi",
    "starlette",
    "starlette.responses",
    "starlette.routing",
    "starlette.middleware",
    "starlette.middleware.cors",
    "starlette.staticfiles",
    # Async support
    "anyio",
    "anyio._backends",
    "anyio._backends._asyncio",
    "sniffio",
    # HTTP
    "httptools",
    "h11",
    "httpx",
    "httpcore",
    # WebSockets
    "websockets",
    "wsproto",
    # MongoDB
    "motor",
    "motor.motor_asyncio",
    "pymongo",
    "pymongo.errors",
    "bson",
    "dns",
    "dns.resolver",
    "dns.rdatatype",
    # Auth
    "jose",
    "jose.jwt",
    "jose.jws",
    "jose.constants",
    "jose.exceptions",
    "jose.backends",
    "jose.backends.cryptography_backend",
    "passlib",
    "passlib.context",
    "passlib.handlers",
    "passlib.handlers.argon2",
    "argon2",
    "argon2.low_level",
    # Pydantic
    "pydantic",
    "pydantic_core",
    "pydantic.fields",
    "pydantic_settings",
    "email_validator",
    # Python dotenv
    "dotenv",
    # Typing extensions
    "typing_extensions",
    # Click (used by uvicorn CLI)
    "click",
    # Multipart form handling
    "multipart",
    "python_multipart",
]

a = Analysis(
    [str(APP_DIR / "run.py")],
    pathex=[str(BACKEND_DIR)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude test dependencies
        "pytest",
        "pytest_asyncio",
        "_pytest",
        # Exclude dev tools
        "IPython",
        "jupyter",
        "notebook",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="CodexJ",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,  # Keep console for server output
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="CodexJ",
)
