import os

from app.utils.utils import get_project_root

BASE_PATH = get_project_root()
MEDIA_PATH = os.path.join(BASE_PATH, "media")
os.makedirs(MEDIA_PATH, exist_ok=True)

ENTRY_TYPE_NAME_MAX_LENGTH = 256
ENTRY_NAME_MAX_LENGTH = 256
JOURNAL_NAME_MAX_LENGTH = 256
JOURNAL_DESCRIPTION_MAX_LENGTH = 512

USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 64
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
